
- name: "Removing operator"
  block:

    - name: "Setting"
      set_fact:
        rob_index_version: "{{ bundle_index_image_version }}"

    - name: "Setting"
      set_fact:
        rob_index_version: "{{ bob_remove_loop }}"
      when:
        - bob_remove_loop is defined
        - bob_remove_loop != ""

    - name: "Setting operator dir name"
      set_fact:
        operator_dir_name: "{{ operator_dir | basename }}"

    - name: "Remove repo '{{ bundle_image_namespace }}/{{ operator_dir_name }}' from 'quay'"
      uri:
        url: "{{ registry_api_http_protocol | default('https') }}://quay.io/api/v1/repository/{{ bundle_image_namespace }}/{{ operator_dir_name }}"
        method: DELETE
        force_basic_auth: yes
        headers:
          Authorization: "Bearer {{ quay_api_token }}"
        status_code: 204
      failed_when: false
      when:
        - quay_api_token is defined
        - quay_api_token != ""

    - name: "Get list of tags for index image from bundle registry"
      uri:
        url: "{{ registry_api_http_protocol | default('https') }}://{{ bundle_registry }}/v2/{{ bundle_index_image_namespace }}/{{ bundle_index_image_name }}/tags/list"
      register: rob_registry_versions
      failed_when: false

    - name: "Removed operator '{{ operator_dir_name }}' from index '{{ bundle_registry }}{{ bundle_index_image_namespace }}/{{ bundle_index_image_name }}' when index exists"
      block:

        - name: "Setting bundle image name"
          set_fact:
            bundle_index_image: "{{ bundle_registry }}/{{ bundle_index_image_namespace }}/{{ bundle_index_image_name }}:{{ rob_index_version }}"
            opm_index_add_extra_args: "--from-index {{ bundle_registry }}/{{ bundle_index_image_namespace }}/{{ bundle_index_image_name }}:{{ rob_index_version }}"

        - name: "Setting 'index rm' container option"
          set_fact:
            boi_index_args: "-c {{ opm_container_tool_index }}"
          when:
            - opm_container_tool_index is defined
            - opm_container_tool_index != ""

        - name: "Remove operator '{{ operator_dir_name }}' from index image {{ bundle_index_image }}"
          shell: "{{ opm_bin_path }} index rm {{ boi_index_args }} --operators {{ operator_dir_name }} --tag {{ bundle_index_image }}  {{ opm_index_add_extra_args }}"
          failed_when: false

        - name: "Tmp quay fix"
          block:
            - name: "Push index image {{ bundle_index_image }} (quay_push_fix #1)"
              shell: "{{ container_tool }} push {{ bundle_index_image }}"
              environment: "{{ proxy_env }}"

            - name: "Pull index image {{ bundle_index_image }} (quay_push_fix #2)"
              shell: "{{ container_tool }} pull {{ bundle_index_image }}"
              environment: "{{ proxy_env }}"
          when:
            - (quay_push_fix is undefined or quay_push_fix|bool)

        - name: "Push bundle image {{ bundle_index_image }}"
          shell: "{{ container_tool }} push {{ container_push_extra }} {{ bundle_index_image }}"
          environment: "{{ proxy_env }}"
          ignore_errors: true

        - name: "Remove temporary bundle export dir '{{ bundle_export_dir_remove }}'"
          file:
            path: "{{ bundle_export_dir_remove }}"
            state: absent

        - name: "Trying to export operator '{{ operator_dir_name }}' from index image {{ bundle_index_image }}"
          shell: "{{ opm_bin_path }} index export {{ boi_index_args }} --package {{ operator_dir_name }} --index {{ bundle_index_image }} --download-folder {{ bundle_export_dir_remove }}"
          register: rob_export_rc

        - name: "Append '{{ operator_dir_name }}' to '{{ bundle_export_dir_remove }}'"
          set_fact:
            bundle_export_dir_remove_op: "{{ bundle_export_dir_remove }}/{{ operator_dir_name }}"

        - name: "Search for all operators '{{ bundle_export_dir_remove_op }}'"
          find:
            paths: "{{ bundle_export_dir_remove_op }}"
            recurse: no
            file_type: directory
          register: rob_operators_find

        - name: "Fail when export works after removal of operator '{{ operator_dir_name }}' from index image {{ bundle_index_image }}"
          fail:
            msg: "Operator '{{ operator_dir_name }}' was not correctly removed from {{ bundle_index_image }} !!! Look in exported directory '{{ bundle_export_dir_remove_op }}' on remote host for more info."
          when: rob_operators_find.files.0 is defined
      when:
        - rob_registry_versions.status == 200

    - name: "Setting operator was removed"
      set_fact:
        operator_removed: true

  tags:
    - always
    - deploy_bundles
    - remove_operator
